FROM tomcat:alpine
MAINTAINER Vinod Godara
WORKDIR $JENKINS_HOME/workspace/devops-assignment/
COPY devops-assignment-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
RUN chmod 755 /usr/local/tomcat/webapps/devops-assignment-0.0.1-SNAPSHOT.war
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run